from pathlib import Path

OUT = Path('main/boards/xingzhi-cube-1.83tft-wifi/mochi_food_assets.h')
SIZE = 28

PAL = {
    'T': (0,0,0,0),
    'K': (86,92,132,255),
    'C': (255,246,233,255),
    'W': (255,255,252,255),
    'B': (154,213,246,255),
    'b': (112,184,238,255),
    'P': (255,161,188,255),
    'p': (255,198,214,255),
    'O': (255,188,128,255),
    'S': (255,150,112,255),
    'G': (255,205,87,255),
    'g': (255,232,145,255),
    'M': (164,229,217,255),
    'R': (177,125,87,255),
    'D': (145,96,70,255),
    'L': (118,188,112,255),
}


def blank(): return [['T']*SIZE for _ in range(SIZE)]
def put(im,x,y,c):
    if 0 <= x < SIZE and 0 <= y < SIZE: im[y][x]=c

def rect(im,x0,y0,x1,y1,c):
    for y in range(y0,y1+1):
        for x in range(x0,x1+1): put(im,x,y,c)

def ellipse(im,x0,y0,x1,y1,c):
    cx=(x0+x1)/2; cy=(y0+y1)/2; rx=max(.5,(x1-x0+1)/2); ry=max(.5,(y1-y0+1)/2)
    for y in range(y0,y1+1):
        for x in range(x0,x1+1):
            if ((x-cx)/rx)**2 + ((y-cy)/ry)**2 <= 1: put(im,x,y,c)

def poly(im,pts,c):
    xs=[p[0] for p in pts]; ys=[p[1] for p in pts]
    for y in range(min(ys),max(ys)+1):
        for x in range(min(xs),max(xs)+1):
            inside=False; j=len(pts)-1
            for i in range(len(pts)):
                xi,yi=pts[i]; xj,yj=pts[j]
                if ((yi>y)!=(yj>y)) and x < (xj-xi)*(y-yi)/(yj-yi+1e-9)+xi: inside=not inside
                j=i
            if inside: put(im,x,y,c)

def line(im,x0,y0,x1,y1,c,w=1):
    dx=abs(x1-x0); sx=1 if x0<x1 else -1; dy=-abs(y1-y0); sy=1 if y0<y1 else -1; err=dx+dy
    while True:
        for oy in range(-(w//2),w//2+1):
            for ox in range(-(w//2),w//2+1): put(im,x0+ox,y0+oy,c)
        if x0==x1 and y0==y1: break
        e2=2*err
        if e2>=dy: err+=dy; x0+=sx
        if e2<=dx: err+=dx; y0+=sy

def fish_cake():
    im=blank()
    poly(im,[(3,10),(8,5),(18,5),(22,8),(26,6),(25,12),(27,16),(23,20),(18,18),(12,22),(5,20),(1,15)],'K')
    poly(im,[(4,10),(9,6),(18,6),(22,9),(25,8),(24,12),(26,15),(22,19),(18,17),(12,21),(6,19),(2,15)],'g')
    poly(im,[(5,11),(10,7),(18,7),(21,10),(22,16),(18,16),(12,20),(7,18),(3,15)],'C')
    poly(im,[(21,10),(26,8),(24,13),(26,17),(21,16)],'O')
    poly(im,[(11,8),(15,5),(17,8)],'O')
    poly(im,[(11,18),(15,22),(17,18)],'O')
    ellipse(im,6,12,8,14,'D'); put(im,7,12,'W'); ellipse(im,8,15,10,17,'P')
    line(im,11,9,17,9,'O'); line(im,11,12,18,12,'O'); line(im,12,15,18,15,'O')
    rect(im,18,11,19,12,'B'); rect(im,19,10,19,13,'B'); rect(im,17,11,20,11,'B')
    put(im,10,6,'W'); put(im,4,16,'W')
    return im

def meal_bowl():
    im=blank()
    ellipse(im,1,9,26,27,'K'); ellipse(im,2,9,25,25,'C')
    rect(im,3,17,24,20,'B'); rect(im,5,20,22,22,'B'); rect(im,8,23,19,24,'W')
    ellipse(im,2,7,25,15,'K'); ellipse(im,3,8,24,14,'W'); ellipse(im,4,9,23,13,'p')
    poly(im,[(8,7),(16,6),(22,10),(17,15),(9,14),(6,11)],'S')
    line(im,9,8,19,11,'g'); line(im,8,10,17,13,'O')
    poly(im,[(6,9),(11,8),(14,10),(11,14),(6,13),(4,11)],'C')
    for x,y in [(3,11),(19,9),(20,13),(13,13)]: ellipse(im,x,y,x+4,y+4,'R')
    rect(im,16,7,17,10,'L'); rect(im,17,8,20,9,'L'); rect(im,18,6,19,10,'L')
    poly(im,[(5,16),(6,14),(7,16),(9,16),(7,18),(8,20),(6,19),(4,20),(5,18),(3,16)],'G')
    put(im,5,10,'W'); put(im,21,11,'g')
    return im

def star_dessert():
    im=blank()
    ellipse(im,2,10,25,23,'K'); ellipse(im,3,10,24,22,'C')
    rect(im,5,18,22,21,'B'); rect(im,7,21,20,23,'C')
    rect(im,11,22,16,25,'B'); rect(im,9,25,18,26,'K'); rect(im,10,25,17,25,'g')
    ellipse(im,6,5,21,18,'C'); ellipse(im,8,4,19,14,'W')
    poly(im,[(10,10),(14,7),(18,9),(19,12),(22,10),(21,14),(18,16),(14,15),(11,17),(8,15)],'G')
    put(im,13,10,'O'); line(im,14,12,17,12,'O')
    ellipse(im,4,7,9,13,'g'); ellipse(im,6,7,10,11,'C')
    ellipse(im,3,14,6,17,'b'); ellipse(im,21,14,24,17,'b'); put(im,4,14,'W'); put(im,22,14,'W')
    ellipse(im,6,14,10,18,'P'); ellipse(im,8,12,12,16,'p'); put(im,9,15,'G')
    poly(im,[(14,1),(15,4),(18,4),(16,6),(17,9),(14,7),(11,9),(12,6),(10,4),(13,4)],'G')
    put(im,14,3,'W'); put(im,19,8,'B'); put(im,7,9,'B')
    return im

ICONS=[('fish',fish_cake()),('meal',meal_bowl()),('dessert',star_dessert())]

lines=['#pragma once','','#include <lvgl.h>','#include <cstddef>','',
       '// Auto-generated by scripts/generate_mochi_food_assets_15j.py.',
       '// 28x28 pastel pixel-art food sprites approved for Mochi Feed V1.','']
for name,im in ICONS:
    data=[]
    for row in im:
        for key in row:
            r,g,b,a=PAL[key]; data.extend((b,g,r,a))
    arr=f'mochi_food_{name}_map'; dsc=f'mochi_food_{name}'
    lines.append(f'alignas(4) static const uint8_t {arr}[] = {{')
    for i in range(0,len(data),16): lines.append('    '+', '.join(f'0x{x:02X}' for x in data[i:i+16])+',')
    lines += ['};', f'static const lv_image_dsc_t {dsc} = {{',
              '    {LV_IMAGE_HEADER_MAGIC, LV_COLOR_FORMAT_ARGB8888, 0, 28, 28, 112, 0},',
              f'    sizeof({arr}),', f'    {arr},', '    nullptr,', '    nullptr', '};','']
lines += ['static const lv_image_dsc_t* const kMochiFoodAssets[] = {',
          '    &mochi_food_fish,','    &mochi_food_meal,','    &mochi_food_dessert,','};',
          'static constexpr size_t kMochiFoodAssetCount =',
          '    sizeof(kMochiFoodAssets) / sizeof(kMochiFoodAssets[0]);',
          'static_assert(kMochiFoodAssetCount == 3);','']
OUT.write_text('\n'.join(lines),encoding='utf-8')
print(f'Generated {OUT} ({OUT.stat().st_size} bytes)')
