from pathlib import Path

OUT = Path("main/boards/xingzhi-cube-1.83tft-wifi/mochi_hud_icon_assets.h")

# 15G uses true bitmap image assets, not LVGL geometry and not icon fonts.
# The palette and pixel language are intentionally derived from the existing
# Mochi art: cream fur, powder blue accents, pink ears/heart and warm gold stars.
PALETTE = {
    ".": (0, 0, 0, 0),
    "K": (86, 92, 132, 255),       # soft blue-violet outline
    "C": (255, 246, 233, 255),    # Mochi cream
    "W": (255, 255, 252, 255),    # highlight
    "B": (154, 213, 246, 255),    # powder blue
    "b": (112, 184, 238, 255),    # deeper blue
    "P": (255, 161, 188, 255),    # petal pink
    "p": (255, 198, 214, 255),    # light pink
    "O": (255, 188, 128, 255),    # peach food
    "G": (255, 205, 87, 255),     # warm star gold
    "g": (255, 232, 145, 255),    # gold highlight
    "M": (164, 229, 217, 255),    # mint (reserved)
    "R": (177, 125, 87, 255),     # warm brown
}

ICONS = {
    "fullness": [
        "................",
        "................",
        ".....KKKKKK.....",
        ".....KOKKGK.....",
        "...KKKKKKKKK....",
        "...KOKKgKKOK....",
        "..KKKKKKKKKKKK..",
        "..KCCCCCCCCCCK..",
        "..KKBBBBBBBBKK..",
        "...KBBWWPPBBK...",
        "...KBBWWPBBBK...",
        "...KBKKKKKKBK...",
        "...KKKKKKKKKK...",
        "................",
        "................",
        "................",
    ],
    "energy": [
        "................",
        "........K.......",
        "........K.......",
        ".......KGK......",
        ".......KGK......",
        "..KKKKKggGKKKKK.",
        "...KGGGggGGGGK..",
        "....KGGggGWGK...",
        ".....KGGGGGK....",
        ".....KGGGGGK....",
        ".....KGGGGGK....",
        "....KKGKKKGKK...",
        "....KKK...KKK...",
        "....K.......K...",
        "................",
        "................",
    ],
    "mood": [
        "................",
        "................",
        "...K.........K..",
        "...Kp.......pK..",
        "...KpKKKKK.KpK..",
        "...KKKCCCCKKpK..",
        "...KKCCCCCCKKK..",
        "..KKCCCCCCCCKK..",
        "..bbCbbCCbbCbb..",
        "..bbCbbCCbbCbb..",
        "..bbPCCPPCCPbb..",
        "..KKCCKCCKCCKK..",
        "...KKCCKKCCKK...",
        "....KKCCCCKK....",
        "......KKKK......",
        "................",
    ],
    "friendship": [
        "................",
        "................",
        "................",
        "...KKKK...KKKK..",
        "...KPPPK.KPPPK..",
        "..KPpWPPKPPPPPK.",
        "..KPppPPPPPPPPK.",
        "..KPPPPPPPPPPPK.",
        "..KPPPPPPPPPPPK.",
        "...KPPPPPPPPPK..",
        "....KKPPPPPKK...",
        ".....KKPPPKK....",
        "......KKPKK.....",
        ".......KKK......",
        "........K.......",
        "................",
    ],
    "coin": [
        "................",
        "......KKKK......",
        "....KKGGGGKK....",
        "...KGGGGGGGGK...",
        "..KGWGggRRGGGK..",
        "..KGGRRgRRgGGK..",
        ".KGGgRRgggRRGGK.",
        ".KGGgggRRgRRGGK.",
        ".KGGggRRRRggGGK.",
        ".KGGggRRRRggGGK.",
        "..KGGggRRggGGK..",
        "..KGGGggggGGGK..",
        "...KGGGGGGGGK...",
        "....KKGGGGKK....",
        "......KKKK......",
        "................",
    ],
}

ORDER = ["fullness", "energy", "mood", "friendship", "coin"]


def bytes_for(rows):
    if len(rows) != 16 or any(len(row) != 16 for row in rows):
        raise SystemExit("Every 15G icon must be exactly 16x16")
    data = []
    for row in rows:
        for key in row:
            if key not in PALETTE:
                raise SystemExit(f"Unknown palette key: {key!r}")
            r, g, b, a = PALETTE[key]
            # LVGL ARGB8888 is represented by lv_color32_t in memory as BGRA.
            data.extend((b, g, r, a))
    return data


lines = [
    "#pragma once",
    "",
    "#include <lvgl.h>",
    "#include <cstddef>",
    "",
    "// Auto-generated by scripts/generate_mochi_hud_assets_15g.py.",
    "// 16x16 pastel pixel-art assets matched to Mochi/background style.",
    "",
]

for name in ORDER:
    data = bytes_for(ICONS[name])
    map_name = f"mochi_hud_{name}_map"
    dsc_name = f"mochi_hud_{name}"
    lines.append(f"alignas(4) static const uint8_t {map_name}[] = {{")
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{x:02X}" for x in data[i:i + 16]) + ",")
    lines.extend([
        "};",
        f"static const lv_image_dsc_t {dsc_name} = {{",
        "    {LV_IMAGE_HEADER_MAGIC, LV_COLOR_FORMAT_ARGB8888, 0, 16, 16, 64, 0},",
        f"    sizeof({map_name}),",
        f"    {map_name},",
        "    nullptr,",
        "    nullptr",
        "};",
        "",
    ])

lines.append("static const lv_image_dsc_t* const kMochiHudIconAssets[] = {")
for name in ORDER:
    lines.append(f"    &mochi_hud_{name},")
lines.extend([
    "};",
    "",
    "static constexpr size_t kMochiHudIconAssetCount =",
    "    sizeof(kMochiHudIconAssets) / sizeof(kMochiHudIconAssets[0]);",
    "static_assert(kMochiHudIconAssetCount == 5);",
    "",
])

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Generated {OUT} ({OUT.stat().st_size} bytes)")
