from pathlib import Path

OUT = Path("main/boards/xingzhi-cube-1.83tft-wifi/mochi_hud_icon_assets.h")

# 15H keeps the same Mochi-matched palette/art from 15G, but renders it as a
# native 20x20 bitmap instead of 16x16. The 1.83-inch panel made 16x16 details
# collapse visually, so the source sprite is enlarged with nearest-neighbour
# sampling to preserve the pixel-art edges without blur.
PALETTE = {
    ".": (0, 0, 0, 0),
    "K": (86, 92, 132, 255),
    "C": (255, 246, 233, 255),
    "W": (255, 255, 252, 255),
    "B": (154, 213, 246, 255),
    "b": (112, 184, 238, 255),
    "P": (255, 161, 188, 255),
    "p": (255, 198, 214, 255),
    "O": (255, 188, 128, 255),
    "G": (255, 205, 87, 255),
    "g": (255, 232, 145, 255),
    "M": (164, 229, 217, 255),
    "R": (177, 125, 87, 255),
}

ICONS = {
    "fullness": [
        "................",
        "................",
        ".....KKKKKK.....",
        ".....KOKKGK.....",
        "...KKKKKKKKK....",
        "...KOKKgKKOK....",
        "..KKKKKKKKKKKK..",
        "..KCCCCCCCCCCK..",
        "..KKBBBBBBBBKK..",
        "...KBBWWPPBBK...",
        "...KBBWWPBBBK...",
        "...KBKKKKKKBK...",
        "...KKKKKKKKKK...",
        "................",
        "................",
        "................",
    ],
    "energy": [
        "................",
        "........K.......",
        "........K.......",
        ".......KGK......",
        ".......KGK......",
        "..KKKKKggGKKKKK.",
        "...KGGGggGGGGK..",
        "....KGGggGWGK...",
        ".....KGGGGGK....",
        ".....KGGGGGK....",
        ".....KGGGGGK....",
        "....KKGKKKGKK...",
        "....KKK...KKK...",
        "....K.......K...",
        "................",
        "................",
    ],
    "mood": [
        "................",
        "................",
        "...K.........K..",
        "...Kp.......pK..",
        "...KpKKKKK.KpK..",
        "...KKKCCCCKKpK..",
        "...KKCCCCCCKKK..",
        "..KKCCCCCCCCKK..",
        "..bbCbbCCbbCbb..",
        "..bbCbbCCbbCbb..",
        "..bbPCCPPCCPbb..",
        "..KKCCKCCKCCKK..",
        "...KKCCKKCCKK...",
        "....KKCCCCKK....",
        "......KKKK......",
        "................",
    ],
    "friendship": [
        "................",
        "................",
        "................",
        "...KKKK...KKKK..",
        "...KPPPK.KPPPK..",
        "..KPpWPPKPPPPPK.",
        "..KPppPPPPPPPPK.",
        "..KPPPPPPPPPPPK.",
        "..KPPPPPPPPPPPK.",
        "...KPPPPPPPPPK..",
        "....KKPPPPPKK...",
        ".....KKPPPKK....",
        "......KKPKK.....",
        ".......KKK......",
        "........K.......",
        "................",
    ],
    "coin": [
        "................",
        "......KKKK......",
        "....KKGGGGKK....",
        "...KGGGGGGGGK...",
        "..KGWGggRRGGGK..",
        "..KGGRRgRRgGGK..",
        ".KGGgRRgggRRGGK.",
        ".KGGgggRRgRRGGK.",
        ".KGGggRRRRggGGK.",
        ".KGGggRRRRggGGK.",
        "..KGGggRRggGGK..",
        "..KGGGggggGGGK..",
        "...KGGGGGGGGK...",
        "....KKGGGGKK....",
        "......KKKK......",
        "................",
    ],
}

ORDER = ["fullness", "energy", "mood", "friendship", "coin"]
SOURCE_SIZE = 16
TARGET_SIZE = 20


def scale_rows(rows):
    if len(rows) != SOURCE_SIZE or any(len(row) != SOURCE_SIZE for row in rows):
        raise SystemExit("Every source icon must be exactly 16x16")
    out = []
    for y in range(TARGET_SIZE):
        sy = min(SOURCE_SIZE - 1, (y * SOURCE_SIZE) // TARGET_SIZE)
        row = []
        for x in range(TARGET_SIZE):
            sx = min(SOURCE_SIZE - 1, (x * SOURCE_SIZE) // TARGET_SIZE)
            row.append(rows[sy][sx])
        out.append("".join(row))
    return out


def bytes_for(rows):
    rows = scale_rows(rows)
    data = []
    for row in rows:
        for key in row:
            if key not in PALETTE:
                raise SystemExit(f"Unknown palette key: {key!r}")
            r, g, b, a = PALETTE[key]
            data.extend((b, g, r, a))
    return data


lines = [
    "#pragma once",
    "",
    "#include <lvgl.h>",
    "#include <cstddef>",
    "",
    "// Auto-generated by scripts/generate_mochi_hud_assets_15g.py.",
    "// 20x20 pastel pixel-art assets enlarged for the 1.83-inch hardware panel.",
    "",
]

for name in ORDER:
    data = bytes_for(ICONS[name])
    map_name = f"mochi_hud_{name}_map"
    dsc_name = f"mochi_hud_{name}"
    lines.append(f"alignas(4) static const uint8_t {map_name}[] = {{")
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{x:02X}" for x in data[i:i + 16]) + ",")
    lines.extend([
        "};",
        f"static const lv_image_dsc_t {dsc_name} = {{",
        "    {LV_IMAGE_HEADER_MAGIC, LV_COLOR_FORMAT_ARGB8888, 0, 20, 20, 80, 0},",
        f"    sizeof({map_name}),",
        f"    {map_name},",
        "    nullptr,",
        "    nullptr",
        "};",
        "",
    ])

lines.append("static const lv_image_dsc_t* const kMochiHudIconAssets[] = {")
for name in ORDER:
    lines.append(f"    &mochi_hud_{name},")
lines.extend([
    "};",
    "",
    "static constexpr size_t kMochiHudIconAssetCount =",
    "    sizeof(kMochiHudIconAssets) / sizeof(kMochiHudIconAssets[0]);",
    "static_assert(kMochiHudIconAssetCount == 5);",
    "",
])

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Generated {OUT} ({OUT.stat().st_size} bytes) with 20x20 HUD sprites")
